# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: SQLake Workshop
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
